// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_uHJ3Ejfia_hOMXplR0ksMd2AdnnN_2o',
    appId: '1:361285898250:web:5b8251c600c5da2c054ff3',
    messagingSenderId: '361285898250',
    projectId: 'mygptmsg',
    authDomain: 'mygptmsg.firebaseapp.com',
    storageBucket: 'mygptmsg.appspot.com',
    measurementId: 'G-2ML0KYLZZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1hVLU5CXa3AhdFOuSrUhgqfP_fTTCpN4',
    appId: '1:361285898250:android:dc74de29533e03f6054ff3',
    messagingSenderId: '361285898250',
    projectId: 'mygptmsg',
    storageBucket: 'mygptmsg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbZGRSg1G1kPTLRR5PvREV4532C5UigHs',
    appId: '1:361285898250:ios:c6c2ac378ba3beec054ff3',
    messagingSenderId: '361285898250',
    projectId: 'mygptmsg',
    storageBucket: 'mygptmsg.appspot.com',
    iosClientId: '361285898250-ntfn508o6b94fc1rvtboedtah6pioma7.apps.googleusercontent.com',
    iosBundleId: 'com.example.messengerDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbZGRSg1G1kPTLRR5PvREV4532C5UigHs',
    appId: '1:361285898250:ios:c6c2ac378ba3beec054ff3',
    messagingSenderId: '361285898250',
    projectId: 'mygptmsg',
    storageBucket: 'mygptmsg.appspot.com',
    iosClientId: '361285898250-ntfn508o6b94fc1rvtboedtah6pioma7.apps.googleusercontent.com',
    iosBundleId: 'com.example.messengerDemo',
  );
}
